### ISSUE TITLE
Driver is not thread safe

### ISSUE THREAD

**Issue by nomis52** [fx5/usbdmx#6]
Hi,

I'm a developer on the Open Lighting Project ( https://github.com/OpenLightingProject/ola ) and we'd like to add support for your devices. However the code provided isn't thread safe since there is no locking provided around the output TDMXArray. This will lead to corrupted DMX frames.

Are there plans to provide a thread safe driver?

**Comment by fx5** [comment]
Closing this, because this driver is intended to keep the api of the legacy driver. I'll probably make a new driver with a better api.
