### ISSUE TITLE
Driver broken on Win10

### ISSUE THREAD

**Issue by CShark** [fx5/usbdmx#7]
Using the new Windows 10, the driver cannot be used anymore, because some api seems to have changed.

Whenever I run e.g. the test tool from Digital Enlightment, it won't work because

    Exception EStringListError in Module usbdmx.dll at 0000E7DD

Therefore the Device is simply broken at the moment and is pretty useless. A fix would be nice, as Microsoft is trying to set Win10 as a standard everywhere.

**Comment by CShark** [comment]
It seems to be a string parse error with the id of the device. When I run the ArtNet Showgate, i get the following interface to choose from
    
    ?☐?W?B?B ???????

After closing the dropdown and reopening it changes to

     ?☐???B?B ?☐?????V

And after that to some other stuff. After you selected the weird ID (which doesn't work of course), the correct ID appears and the device starts working as soon as you select it.

**Comment by fx5** [comment]
Sorry for the late Response. This is probably a problem with Windows 8.1/Windows 10. Please try this program to fix it: https://fx5.de/FX5-Installer.exe
