### ISSUE TITLE
Artnet-DMX Node

### ISSUE THREAD

**Issue by raumfisch** [fx5/usbdmx#8]
Hey, 
i'm currently trying to set up the FX5 Interface on Linux and Mac. I read that there should be something like an Artnet <> DMX program that makes it possible to make this device running with various artnet controller softwares, but i'm not able to find it. 

Is there any documentation on this? Is there a program for this?

Thanks, 

Jan

**Comment by fx5** [comment]
There's an artnet program in this archive: http://www.digital-enlightenment.de/prusbdmx.php3

Not related to this driver. Closing.
